#!/bin/sh
# Vendored stand-in for codex-wire's gen-codex-home.sh, for the row-7 CONTRACT row.
#
# ⛔ THIS IS NOT THE REAL GENERATOR AND MUST NEVER BE DESCRIBED AS ONE. It performs the four
# operations the real one performs on an EXISTING home, quoted from gen-codex-home.sh lines 27-88
# and reproduced in the spec's §2:
#     mkdir -p "$SPAWN_HOME"                 # idempotent, non-destructive
#     ln -sfn "$HOME/.codex/auth.json" ...   # re-links the credential
#     cat > "$SPAWN_HOME/config.toml"        # overwrites ONLY config.toml
#     chmod 600 "$SPAWN_HOME/config.toml"
#
# It exists because the real generator lives outside this repository, so a row bound to its
# absolute path can never pass in CI — and a gate that cannot go green is one nobody reads.
# What this row tests is OUR contract: re-provisioning must not clobber retained state.
# Whether the REAL generator still performs exactly these operations is a separate claim,
# checked by the row that runs only when GEN_CODEX_HOME resolves.
set -eu
: "${AGENT_ID:?AGENT_ID required}"
SPAWN_HOME="${HOME}/.wire/codex-spawn/${AGENT_ID}"
mkdir -p "$SPAWN_HOME"
ln -sfn "${HOME}/.codex/auth.json" "${SPAWN_HOME}/auth.json"
cat > "${SPAWN_HOME}/config.toml" <<TOML
# regenerated by the vendored provisioner
model = "${CODEX_MODEL:-gpt-5.5}"
TOML
chmod 600 "${SPAWN_HOME}/config.toml"
printf '%s\n' "$SPAWN_HOME"
